### ISSUE TITLE
Parameter not working

### ISSUE THREAD

**Issue by Spanjoekel** [silverhack/monkey365#52] opened 2023-05-31 06:42 UTC
Hi Silverhack,

Thank you for the quick release, i tested the new Microsoft365 scan and it works.
Just wanted to let you know, the following parameter is giving an errors.

- all_subscriptions

Let me know if i can help with anything.

Regards,
Spanjoekel

**Comment by silverhack** [comment] 2023-05-31 07:50
Hi @Spanjoekel, 

Could you please post it which errors are you exactly seeing? A debug log or error message would help. 

Cheers

**Comment by Spanjoekel** [comment] 2023-05-31 13:21
I filtered out the -IncludeAzureAD parameter, when i used this today with the Azure and Microsoft365 instance, they both worked fine, only the all_subscriptions still give the error shown above

**Comment by silverhack** [comment] 2023-06-01 07:51
Hi @Spanjoekel, 

Thanks for letting me know about that and now I can reproduce your issue. Some variables were reworded to comply with PowerShell best practices. and there is a missing alias for the `AllSubscriptions` parameter. 

Solution would be to include the `all_subscriptions` alias. 

In the meantime, you can use the `AllSubscriptions` parameter, as shown below:

```PowerShell
Invoke-Monkey365 -Instance Azure -Analysis All -IncludeAzureAD -AllSubscriptions -ExportTo HTML
```

Cheers,

**Comment by Spanjoekel** [comment] 2023-06-01 18:31
> 

Hi @silverhack ,

Why not leave it like this and replace the parameter in the docs. i can make this work without a _

Regards

**Comment by silverhack** [comment] 2023-06-01 18:49
Hey @Spanjoekel, 

You're right about that, but I'd like to add some alias to help people in the transition from *nix systems to PowerShell. For example people that are comfortable with *nix shells probably won't be comfortable with flags such as the -includeAzureAD, -Promtvehavior, etc.., and for that reason, it would be great to add this feature to Monkey365.

Hope that helps :D

**Comment by silverhack** [comment] 2023-06-30 20:10
Hi all, this is now fixed on dev branch. Please do let me know if you have any issue. 

Cheers

**Comment by DM01187** [comment] 2023-07-17 12:38
Hi @silverhack,
I would like to contact again today, as I have not found a solution so far.

When running from:

$param = @{
    Instance = 'Microsoft365';
    Analysis = 'SharePointOnline';
    PromptBehavior = 'SelectAccount';
    IncludeAzureAD = $true;
    ExportTo = 'HTML';
}
$assets = Invoke-Monkey365 @param

I keep getting the message:


WARNUNG: [11:01:10:113] - [Get-MonkeyCSOMSitesForUser] - Unable to get site properties using xyz account - warning - S25111 - SPSUnableToGetSites

The $ScanSubSites variable cannot be retrieved because it has not been set.

What I am doing wrong?

Thanks for your quick reply

Dirk

**Comment by silverhack** [comment] 2023-07-18 08:30
Hi @DM01187, 

It seems MS is blocking some first-party apps from connecting SharePoint Online, and a [new issue](https://github.com/silverhack/monkey365/issues/55) was opened.

**Comment by silverhack** [comment] 2023-08-11 16:07
It's now fixed on dev branch. It will be merged to main branch asap

**Closed by silverhack** 2023-08-11 16:07 UTC
Labels: bug
