### ISSUE TITLE
[Bug]:  Monkey365 causes exception when Analysis and IncludeEntraId parameters are not provided

### ISSUE THREAD

**Issue by sssseossss** [silverhack/monkey365#98] opened 2024-04-25 09:45 UTC
**What happened?**  
using Pwsh7.4 
Donwloaded newest version from develop branch, imported module, then invoke-monkey365 -> input credentials and get the following:
InvalidOperation: C:\users\XXXX\downloads\powershell-7.4.2-win-x64\Modules\monkey365\Invoke-Monkey365.ps1:455
Line |
 455 |              switch ($O365Object.Instance.ToLower()){
     |                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | You cannot call a method on a null-valued expression.

**How to reproduce it**  
as described above

**Expected behavior**  
Program should just work

**Screenshots or Logs**  
all info noted above
**From where are you running Monkey365?**  
Please, complete the following information:
 - Resource: [Docker container, workstation)  workstation
 - OS: [e.g. Windows, Linux, etc. ] Windows 11
 - PowerShell Version [`$PsVersionTable`]: 7.4.2
 - Monkey365 Version: Newest from develop branch
 - Others:

**Additional context**

**Comment by silverhack** [comment] 2024-04-25 14:11
Hi @sssseossss, 

Renamed the issue as the title is not reflecting the actual issue. 

Firstly, the execution is not a bug and you're executing Monkey365 incorrectly. Please, see docs about how to correctly execute Monkey365 against supported environments. 

The instance parameter must be populated when the -IncludeEntraId is not set. Valid options are Azure and Microsoft365. You can find more information [here](https://silverhack.github.io/monkey365/basic-usage/). 

On the other hand, Monkey365 should raise an error when both parameters are not provided. It's a bug and should be fixed shortly. 

Thanks for using Monkey365!

**Comment by silverhack** [comment] 2024-06-10 17:15
This is now updated in [main release](https://github.com/silverhack/monkey365/releases/tag/v0.91.3-beta). 

Cheers,

**Closed by silverhack** 2024-06-10 17:15 UTC
Labels: bug
