### ISSUE TITLE
Running into redirect issue when using Instance M365, Azure seems to work fine though 

### ISSUE THREAD

**Issue by mike16329** [silverhack/monkey365#75] opened 2023-11-01 20:07 UTC
I am receiving the following error after completing the interactive login/MFA:

 AADSTS50011: The redirect URI 'https://login.microsoftonline.us/organizations' specified in the request does not match the redirect URIs configured for the application 'fb78d390-0c51-40cd-8e17-fdbfab77341b'. Make sure the redirect URI sent in the request matches one added to your application in the Azure portal. Navigate to https://aka.ms/redirectUriMismatchError to learn more about how to fix this. 

This occurs when I run 

$param = @{
    Instance = 'Microsoft365';
    Analysis = 'ExchangeOnline';
    PromptBehavior = 'SelectAccount';
    Environment = 'AzureUSGovernment';
    ExportTo = 'HTML';
}
Invoke-Monkey365 @param

I don't see app fb78d390-0c51-40cd-8e17-fdbfab77341bin Azure AD at all

**Comment by silverhack** [comment] 2023-11-02 00:29
Hey @mike16329,  

Thanks for submitting this. That error is rare, as it seems that the reply url is correct for GCC environments as explained [here](https://techcommunity.microsoft.com/t5/exchange-team-blog/changes-to-the-reply-url-list-in-exchange-online-powershell/ba-p/2112735). 

Could you please elaborate? Could you please also check if you can connect through exchange online Powershell module? 

Thanks

**Comment by mike16329** [comment] 2023-11-02 12:39
Of course. I extracted the zip for monkey365-main and renamed it Monkey365 and placed it in program files. I then import it with the command Import-Module C:\"program files"\monkey365,the command seems to work successfully and shows no errors. I then, from the C:\"program files"\monkey365 directory, ran 

$param = @{
Instance = 'Microsoft365';
Analysis = 'ExchangeOnline';
PromptBehavior = 'SelectAccount';
Environment = 'AzureUSGovernment';
ExportTo = 'HTML';
}
Invoke-Monkey365 @param

It brings up the interactive login box, I log in with my global admin GCCH account, complete MFA, and then it gives me the URI redirect error. I am able to successfully log into the exchange online PowerShell module using the following command format Connect-ExchangeOnline -UserPrincipalName user@mydomain.com -ExchangeEnvironmentName O365USGovGCCHigh

**Comment by silverhack** [comment] 2023-11-06 07:09
Hi @mike16329, 

Firstly, thank you for replying so promptly and thanks for letting me know about this issue. It's really appreciated. 

I had faced this problem when authentication library for Desktop is used, and after researching a bit into the MS documentation I think where the problem is, so I just [updated](https://github.com/silverhack/monkey365/commit/2c2043e4d8e62850c2d4f28484c03e8ee236cd0a) the [develop branch](https://github.com/silverhack/monkey365/tree/develop) with an small update. 

Could you please check if it works for you?

Thanks in advance,

**Comment by silverhack** [comment] 2023-11-07 17:16
Hi @mike16329, 

It is confirmed that MS documentation is wrong regarding Reply Urls with GCC tenants. Documentation states that Reply Url for GCC High is https://login.microsoftonline.us/organizations, which is wrong and should be https://login.microsoftonline.us/organizations/oauth2/nativeclient for .NET applications. 

The dev branch was updated and main branch will be updated with this fix among others on this week.

**References**

[https://login.microsoftonline.us/organizations/oauth2/nativeclient](https://login.microsoftonline.us/organizations/oauth2/nativeclient)

Cheers,

**Comment by silverhack** [comment] 2023-12-22 17:50
Fixed in main branch.

Cheers,

**Closed by silverhack** 2023-12-22 17:50 UTC
Labels: bug
