### ISSUE TITLE
[Bug]: "Access has been blocked by Conditional Access policies. The access policy does not allow token issuance."

### ISSUE THREAD

**Issue by Argandov** [silverhack/monkey365#37] opened 2022-11-23 15:38 UTC
This issuance is not about a bug in the application, but as an issue I'm having in my specific use case. It must be an error on my side and something I'm not doing right.

I was installing Monkey365 for the first time and trying to use it against a test M365 account, NOT on Azure. The user has Global Reader for Microsoft 365 tenant, not on Azure. This user does not have access to any Azure service. 

When I try to authenticate using Monkey365, I get an authentication error, stating the Sign-in was successful but there are no sufficient permissions.

- Client PC running Monkey365: Windows 10 Pro VM
- Permissions on user: Microsoft 365 **only**, Global reader & Security reader
- Versions: Latest Powershell and latest Monkey365 (I just installed it from Main branch on 22 Nov)

The Monkey365 Docs does not state additional permissions, Conditional Access allowance, etc. That I should kick the tires on before I use it.

Monkey365 states that users can audit Microsoft 365 **_OR_** Azure. That's why I think I should be able authenticate and review a Microsoft 365 Tenant without the need for any Azure authentication, but Monkey365 is using Azure Powershell (Image no. 3)

---

Image 1: Screenshot for Monkey365 authentication & Error:
![image](https://user-images.githubusercontent.com/67169222/203583526-94d44935-15ed-4229-b867-c79832ca4534.png)

Image 2: Upon reviewing the alerts in the Microsoft Console (Admin center), I see the following marker, which is interesting:
![image](https://user-images.githubusercontent.com/67169222/203585049-11c584f5-f222-445d-ab8c-da35bf247681.png)

Image 3: Full error log on Authentication error:
![image](https://user-images.githubusercontent.com/67169222/203587218-26c71bfa-11e0-4a8b-9912-d965822e2101.png)

**Comment by silverhack** [comment] 2022-11-23 20:03
Hi @Argandov thanks for submitting this. 

It's not a bug, and it's more about conditional access issues with your tenant. 

Firstly, and according to the error message, it seems that you are trying to pass **all** option to the **-Analysis** flag. Please, note that the **All** option is not available yet in Microsoft 365 scans. 

Secondly, Azure AD authentication (Graph and MSGraph APIs) is mandatory in order to get information about your Tenant, so this is **by design**. If your tenant is configured with Conditional Access policies targeting these applications (i.e. Azure AD), your user should be part of allowed groups or should be excluded from these policies.

And finally, documentation about Conditional Access was not included in document because It's obvious that you must know that the user must be created before a role and/or conditional access policies can be assigned to him. So, if conditional access policies are in place, your user should be part of allowed groups or should be excluded from these policies in order to be allowed to sign into isolated portals.

Please, read the [Microsoft 365 options](https://silverhack.github.io/monkey365/configuration/microsoft365-options/), as well as the [basic usage](https://silverhack.github.io/monkey365/basic-usage/) sections in [docs](https://silverhack.github.io/monkey365/). 

As an example, and if your user is allowed to login into Azure Ad and SharePoint online, the following command will work 

$asset = Invoke-Monkey365 -ExportTo PRINT -PromptBehavior SelectAccount -Instance Microsoft365 -Analysis SharepointOnline

Hope that helps.
Cheers,

**Comment by Argandov** [comment] 2022-11-24 18:19
Hi, Thank you for your response. I'll try to address your comments one by one

- For the "All" flag, yes, I made the mistake of sharing the wrong Powershell screenshot (Please ignore what flags and errors I get in Monkey365)
- Is it mandatory that my user being allowed to log into Azure AD? This user's scope is only for Microsoft 365 (At the moment I am testing the M365 scanning functionality of Monkey, not on Azure - That comes later). This is the first time I work with Microsoft 365 through Powershell, so I am getting familiar with the process. This user can access the Web UI for Office, Admin Center, Purview, etc. But NO Azure (This was on purpose). So, according to the [Monkey 365 Docs](https://silverhack.github.io/monkey365/permissions/), I should be able to audit **exclusively M365 environment** with no need for an Azure permission, since they are **sepparate** (That is what I understand from the docs).

What am I missing or doing wrong?

I will check out the CAPs tonight

**Comment by JArmandoG** [comment] 2022-11-24 18:21
So I just checked on my CAPs and there are none that wouldn't allow this dummy user to access anything. What else should I check? 

Maybe this issue can help document in a little bit more detailed way how Monkey365 operates?

**Comment by silverhack** [comment] 2022-11-25 09:51
Hi @Argandov and @JArmandoG, 

As far as I can see from your comments, I think that you might have misunderstood some concepts. Microsoft 365 uses Azure AD to manage all identities. This is **by design** and this is how Microsoft 365 has always worked. Please see the [Microsoft docs](https://learn.microsoft.com/en-us/microsoft-365/enterprise/azure-integration?view=o365-worldwide) about how Azure AD integrates with Microsoft 365.

On the other hand, probably you both both don't know which policy is blocking you, since it's not specified in the error message. So in order to get more details, you should go to your Azure AD and check the policy:

1.  Go to Sign-in Logs blade (https://portal.azure.com/#view/Microsoft_AAD_IAM/ActiveDirectoryMenuBlade/~/SignIns)
2. Search for failed logon attempts, or filter by your username
3. Click on the failed log-in request and click on **Conditional Access** to see which policies have been applied
4. The Policies that have as a result **Failure** and **Grant Controls** set on **Block** are the ones that are preventing the user from login successfully

See example below:

<img width="521" alt="cap" src="https://user-images.githubusercontent.com/5271640/203952347-957e8fcf-1484-4e21-9cd0-38692e70020b.PNG">

Hope that helps, 
Cheers

**Comment by Argandov** [comment] 2022-11-25 14:22
Hi @silverhack thank you so much for your detailed response! 🙏 I will be working on this! I'm still learning the Microsoft universe

**Comment by Argandov** [comment] 2022-12-16 14:58
I fixed this on my side, and now I get a new error because my user, although has access to the web consoles, has no active subscriptions. Is there an option for using Monkey365 with something similar to the `--allow-no-subscriptions` in the Azure-cli?

**Comment by silverhack** [comment] 2022-12-16 15:33
Hey @Argandov happy to see you fixed it :D 

Regarding your question, the -IncludeAzureActiveDirectory flag in Monkey365 will do the trick. The following command can be used to scan an Azure AD tenant with an user with no active subscriptions assigned:

Invoke-Monkey365 -ExportTo CSV -PromptBehavior SelectAccount -IncludeAzureActiveDirectory

Cheers,

**Comment by Argandov** [comment] 2022-12-21 18:06
As you can see, I'm testing Monkey 365 for 2 different, desired scenarios in my use case:
* Azure CIS Benchmark compliance
* Microsoft 365 CIS Benchmark compliance

**Closed** 2023-05-06 02:10 UTC
Labels: not a bug, no-issue-activity
